---
- name: Launch Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ app_dest }}"
    state: present
  register: result   # ✅ Correct

- name: Show results
  ansible.builtin.debug:
    var: output

# - name: Launch Docker Compose
#   command: docker compose -f docker-compose.prod.yml up -d
#   args:
#     chdir: "{{ app_dest }}"
  